@startuml
'https://plantuml.com/class-diagram

class Person {
    - name: String
    - age: int
    - address: Address
    # phone_number: long
    + walk()
    + talk()
}

class Address {
    - street: String
    - city: String
    - zipCode: String
    + toString()
}

Person --> Address : has
@enduml